<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-TSE6K3A" ignored="0" name="RetryMultipleTest" tests="18" failures="6" timestamp="2022-10-26T20:55:30 IST" time="0.209" errors="0">
  <testcase name="Test02" time="0.017" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test02 -->
  <testcase name="Test02" time="0.005" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test02 -->
  <testcase name="Test02" time="0.003" classname="retry.Test001">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retry.Test001.Test02(Test001.java:19)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test02 -->
  <testcase name="Test03" time="0.002" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test03 -->
  <testcase name="Test03" time="0.004" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test03 -->
  <testcase name="Test03" time="0.002" classname="retry.Test001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry.Test001.Test03(Test001.java:26)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test03 -->
  <testcase name="Test1" time="0.006" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retry.Test001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="retry.Test001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry.Test001.Test1(Test001.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test02" time="0.003" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test02 -->
  <testcase name="Test02" time="0.004" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test02 -->
  <testcase name="Test02" time="0.002" classname="retry.Test002">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at retry.Test002.Test02(Test002.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test02 -->
  <testcase name="Test03" time="0.002" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test03 -->
  <testcase name="Test03" time="0.005" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test03 -->
  <testcase name="Test03" time="0.002" classname="retry.Test002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry.Test002.Test03(Test002.java:24)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- Test03 -->
  <testcase name="Test1" time="0.003" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retry.Test002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.006" classname="retry.Test002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at retry.Test002.Test1(Test002.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
</testsuite> <!-- RetryMultipleTest -->
